version: "3"

services:
  mongo:
    image: mongo:5.0.15
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: fun7dbuser
      MONGO_INITDB_ROOT_PASSWORD: fun7dbpass
      MONGO_INITDB_DATABASE: fun7
    ports:
      - "27017:27017"
  mongo-data-seeder:
    build: mongo.init.d/.
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/fun7
      MONGO_USER: fun7dbuser
      MONGO_PASSWORD: fun7dbpass